### ISSUE TITLE
support set break point from CLI parameters.

### ISSUE THREAD

**Issue by yuhuihu** [cansarigol/pdbr#21]
ipdb can be used like this:

ipdb -c 'b wantToBreakInFile:100'   launcher.py

So Should we pass the parameter "-c" to pdb ?

**Comment by cansarigol** [comment]
good idea, thanks @yuhuihu . I will be working on it when I get a chance.

**Comment by cansarigol** [comment]
Hi @yuhuihu it is fixed by v0.6.9.

https://github.com/cansarigol/pdbr#as-a-script
