### ISSUE TITLE
print as default action when DataFrame variable entered

### ISSUE THREAD

**Issue by zacclery** [cansarigol/pdbr#22]
In ipdb you can type df (for example) in terminal to view a summary of a dataframe object, however in pdbr it it tries to assert the truth value which is less useful:

```
(Pdbr) df
*** ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by cansarigol** [comment]
thanks for report @zacclery  and it is fixed by v0.6.8
