### ISSUE TITLE
setup.cfg file path

### ISSUE THREAD

**Issue by phgz** [cansarigol/pdbr#25]
Hi,

Would you be open to add an environment variable to point towards which file should be use for `pdbr` config, since now it looks like that the invocation must be made in the same folder where `setup.cfg` resides, or is there another way to do it? 

Perhaps also, it could look in `$XDG_CONFIG_HOME/pdbr/pdbr.cfg`.

I can take care of it if you will accept the PR.

Thanks.

**Comment by cansarigol** [comment]
Hi @philipGaudreau yes you are right, there is only same folder option right now. would be great if you have a look at it. 

And also i was planning to include `pyproject.toml` support. If you want, can include it as well.

Thanks
