### ISSUE TITLE
Updating rich dependency to include 12.x

### ISSUE THREAD

**Issue by jorisroovers** [cansarigol/pdbr#34]
Thanks for creating pdbr, I just discovered it and it looks amazing! It seems more feature-rich for my debugging workflow than e.g. [pdbpp](https://github.com/pdbpp/pdbpp) which I've been using until now.

Would it be possible to update the dependencies to support rich 12.x?
Our app currently uses rich 12.x and so we can't add pdbrr as a dev dependency as it strictly requires 10.x.

I've got a workaround by installing pdbrr globally and then using `virtualenv .venv --system-site-packages` to create a virtualenv for our app that also includes pdbrr, but that's definitely fragile.

It looks like this line needs a bump, but I'm not sure if there's other places that require changes:

https://github.com/cansarigol/pdbr/blob/7cbe96170e4960392588b519dfbfb62e2714fa42/pyproject.toml#L26

Thanks!

**Comment by cansarigol** [comment]
@jorisroovers Hi. thanks for that. I bumped the version. You can use 0.7.1
