### ISSUE TITLE
add prompt_toolkit to dependencies

### ISSUE THREAD

**Issue by matan-h** [cansarigol/pdbr#4]
prompt_toolkit was not added to dependencies in pyproject (imported in this [line](https://github.com/cansarigol/pdbr/blob/e1d19d5234a33b86d4c4fb3c6019b7224ed87012/pdbr/_pdbr.py#L7))

to your [pyproject.toml](https://github.com/cansarigol/pdbr/blob/master/pyproject.toml)
so when importing pdbr it raise:
```pytb
ModuleNotFoundError: No module named 'prompt_toolkit'
```

**Comment by cansarigol** [comment]
Thanks for the issue again @matan-h .
