### ISSUE TITLE
pyreadline3

### ISSUE THREAD

**Issue by KyleKing** [cansarigol/pdbr#41]
Hi, I was testing out this package and noticed that for Windows you may want to update to `pyreadline3`, which is an actively maintained fork of `pyreadline`. See: https://github.com/pyreadline3/pyreadline3#pyreadline3

https://github.com/cansarigol/pdbr/blob/d8d589ee00a400ef36e952a32eae735ec755eb41/pyproject.toml#L31

Could be:

```toml
pyreadline3 = {version = "^3.4.1", markers = "sys_platform == \"win32\""}
```

**Comment by KyleKing** [comment]
This upgrade would probably fix the Windows CI issues;

```sh
x = <bound method BaseMode.self_insert of <EmacsMode>>

    def callable(x):
>       return isinstance(x, collections.Callable)
E       AttributeError: module 'collections' has no attribute 'Callable'

.nox\test\lib\site-packages\pyreadline\py3k_compat.py:8: AttributeError
```

From: https://github.com/cansarigol/pdbr/actions/runs/3222886498/jobs/5272415663

**Comment by cansarigol** [comment]
Thanks @KyleKing I changed the package and worked.
