### ISSUE TITLE
(V)ars get distorted view

### ISSUE THREAD

**Issue by fertingoff** [cansarigol/pdbr#53]
First of all, thanks for pdbr. It's amazing and I use it every day now! Everyting works great, except I have a bug in table view.
For instance, I have three args, but it partially shows only one and the view is distorted (pdbr prompt is horizontally offset).
UPD: Similar issue with vt command now.
UPD 2: Before it was great, now it happens from time to time. Not sure what cause it, I don't change anything in related code.

I'm using v0.8.2
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/5535103/222623629-7d3f2024-6d0f-4515-9fb7-85e39616883a.png">

**Comment by cansarigol** [comment]
Hey @fertingoff  thanks for your feedback. I cannot reproduce the problem. could you give me a bit detail like when it is happening and what 'locals()' shows.

**Comment by fertingoff** [comment]
It's happening only with one file (async), everything else works as intended. I suggest to close.
