### ISSUE TITLE
Colorizing special objects whose repr contains `[` (example: `torch.Tensor` or `np.ndarray`)

### ISSUE THREAD

**Issue by dendenxu** [cansarigol/pdbr#57]
Thanks for the amazing work! I loved `pdbr` at the first sight!🥰
However, there's one small caveat:
**The color is lost when printing special objects whose `repr` contains a `[` character.**

Upon deeper inspection, I found that the `_print` method of `RichPdb` will try to render the markup color of the string if a `[` is present. This would result in `torch.Tensor` and `np.ndarray` or any objects whose string representation contains a `[` having no color.
https://github.com/cansarigol/pdbr/blob/86dc66cf2c9d6c6961305a0b37fb5c5ff6200234/pdbr/_pdbr.py#L399
https://github.com/cansarigol/pdbr/blob/86dc66cf2c9d6c6961305a0b37fb5c5ff6200234/pdbr/_pdbr.py#L395-L411

Example:
![image](https://user-images.githubusercontent.com/43734697/231694692-403d78f2-5c06-4fea-8184-d433e418c9d2.png)
Here we can successfully print a `torch.Tensor` with color using a plain `console.print`, while the color is lost when directly submitting the variable through `pdbr`. Printing numbers or strings is OK.
![image](https://user-images.githubusercontent.com/43734697/231695746-7919bb09-b335-468e-8fb8-58bdd3467e7e.png)
![image](https://user-images.githubusercontent.com/43734697/231696089-da69f944-ede0-42d4-8d09-a9d8f02dcba7.png)
Printing the rendered "markup" using `console.print` leads to the same result as submitting the variable directly.

Is it possible to expose an option in `pdbr` to disable or enable the handling of markup texts? After all, it's quite often for a lot of users to inspect a `torch.Tensor` or `numpy` array. Or do you have other suggestions on how I could print these variables directly in the debugger prompt with color? 🥰Thanks!

**Comment by cansarigol** [comment]
Hi @dendenxu I'm sorry to hear you're having trouble. I was also not sure when I was adding it :smile_cat. The primary purpose was to interpret  `__repr__` functions covered by `rich.console` correctly. I tried to fix both problems. Hence now I seek `[/` closure character instead of only `[`character. What do you think about it?

**Comment by dendenxu** [comment]
Thanks for the quick reply! I think it's awesome. I couldn't think of any common `repr` containing `[/` except for `rich`'s markup syntax.
