### ISSUE TITLE
print less for `ll` (`longlist`)

### ISSUE THREAD

**Issue by dendenxu** [cansarigol/pdbr#59]
Hi! It's me again.

I notice that the `ll` in pdbr prints the whole source file for the current frame instead of only printing the current function (as in `ipdb`). This can sometimes make debugging a little bit clumsy since we might need to scroll up through a lot of unrelated code to locate the actual frame. Although `l` gives a more compact output, it's often not enough to see just the 10 lines around the cursor.

In `ipdb` (actually in `IPython`), [they use `inspect` to locate the actual line range](https://github.com/ipython/ipython/blob/9c07131ad450854fd265895e0b79cc0b89ef72d4/IPython/core/debugger.py#L674-L696) of the current frame. I suppose we could take a similar approach and pass the `line_range` to `_get_syntax_for_list`?

```python
    def getsourcelines(self, obj):
        lines, lineno = inspect.findsource(obj)
        if inspect.isframe(obj) and obj.f_globals is self._get_frame_locals(obj):
            # must be a module frame: do not try to cut a block out of it
            return lines, 1
        elif inspect.ismodule(obj):
            return lines, 1
        return inspect.getblock(lines[lineno:]), lineno+1

    def do_longlist(self, arg):
        """Print lines of code from the current stack frame.

        Shows more lines than 'list' does.
        """
        self.lastcmd = 'longlist'
        try:
            lines, lineno = self.getsourcelines(self.curframe)
        except OSError as err:
            self.error(err)
            return
        last = lineno + len(lines)
        self.print_list_lines(self.curframe.f_code.co_filename, lineno, last)
    do_ll = do_longlist
```

i.e. replace the `with_line_range` argument here with `line_range` and set the default to `None`.
https://github.com/cansarigol/pdbr/blob/234106e937e1ed80f0ec5fce0978fc437cb4f71b/pdbr/_pdbr.py#L128-L142
And `do_list` could invoke `_get_syntax_for_list` with no arguments and `do_longlist` with the line_range obtained from `inspect`?

What do you think?

**Comment by cansarigol** [comment]
Hi @dendenxu it looks more useful than current one as you said. Feel free to create a PR for this. Thanks again.

**Comment by dendenxu** [comment]
I created a PR(#60).

`ll` without #60:
<img width="516" alt="1681629796436_5D497220-A967-4b0a-A3CE-0CE164E264B9" src="https://user-images.githubusercontent.com/43734697/232280473-7e8417b9-7002-48ed-9671-b61a8f220148.png">

`ll` with #60:
<img width="597" alt="1681629537894_32D9514C-4875-4838-89DA-440643951C7E" src="https://user-images.githubusercontent.com/43734697/232280487-c49e2b45-b4a2-4f24-bbf3-a6a2374cdd22.png">

`l` with #60
<img width="618" alt="1681629527342_BD866645-8DA7-4ada-8519-C7CD0E14924F" src="https://user-images.githubusercontent.com/43734697/232280502-a82f9d2f-2b9b-41c1-9a05-68d773e6205b.png">

**Comment by cansarigol** [comment]
Neat job, thanks
