### ISSUE TITLE
Feature request: Add guide to install `pdbr` to `sys.excepthook`.

### ISSUE THREAD

**Issue by hacker-DOM** [cansarigol/pdbr#66]

**Comment by cansarigol** [comment]
@hacker-DOM Could you review that [PR](https://github.com/cansarigol/pdbr/pull/67) whether it covers what you expected?

**Comment by hacker-DOM** [comment]
Nice! I could give it a stot early next week

**Comment by hacker-DOM** [comment]
That works, thanks!!
