### ISSUE TITLE
Incomplete code in traceback 

### ISSUE THREAD

**Issue by ashish10alex** [cansarigol/pdbr#8]
Hi, the library show's incomplete code when the breakpoint is set as shown in the figure. 

Im using -
 Python 3.7.10
Development environment - Mac OS Catalina 10.15.7

<img width="812" alt="Screenshot 2021-07-14 at 17 26 02" src="https://user-images.githubusercontent.com/34306898/125657973-c69a702e-146c-47a1-b175-0c62d884bee0.png">

**Comment by cansarigol** [comment]
@ashish10alex Thanks for the issue. It is fixed by v0.5.8

**Comment by ashish10alex** [comment]
Thanks,  @cansarigol. This does fix the incomplete code but breaks `l(list)` code functionality as shown in the screenshot. 
<img width="802" alt="Screenshot 2021-07-15 at 11 29 00" src="https://user-images.githubusercontent.com/34306898/125773850-08cf2d94-6019-43f5-9ca0-7b2be44c36ca.png">

**Comment by cansarigol** [comment]
@ashish10alex Thanks again. now should be ok with v0.5.9

**Comment by ashish10alex** [comment]
Awesome, love the tool 👍
